apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::425443463152:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-3wdp65YOzvJs
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::425443463152:role/UdacityFlaskDeployCBKubectlRole
      username: codebuild
      groups:
        - system:masters

