# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::425443463152:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-3wdp65YOzvJs
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::425443463152:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-22T16:39:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2867"
  uid: 4984fca5-d486-4687-a1a5-3b9d7c7aa7a4
