apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::425443463152:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-3wdp65YOzvJs
      groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      - rolearn: arn:aws:iam::425443463152:role/UdacityFlaskDeployCBKubectlRole
      username: build
      - rolearn: arn:aws:iam::425443463152:role/UdacityFlaskDeployCBKubectlRole
      username: codebuild
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-22T16:39:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "38759"
  uid: 4984fca5-d486-4687-a1a5-3b9d7c7aa7a4
